spring.application.name=thewoodnest

spring.datasource.url=jdbc:postgresql://localhost:5432/thewoodnest?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true